---
name: ((deployment-name))

releases:
- name: cf-rabbitmq
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq
  instances: 3
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
    properties:
      rabbitmq-server:
        version: ((rabbitmq_version))
        plugins:
        - rabbitmq_management
        - rabbitmq_mqtt
        - rabbitmq_stomp
        ports:
        - 5672
        - 5671
        - 1883
        - 8883
        - 61613
        - 61614
        - 15672
        - 15674
        administrators:
          management:
            username: ((rabbitmq-management-username))
            password: ((rabbitmq-management-password))
          broker:
            username: ((rabbitmq-broker-username))
            password: ((rabbitmq-broker-password))
        cookie: ((rabbitmq-cookie))
        cluster_partition_handling: ((cluster-partition-handling-strategy))
  vm_type: n1-highmem-4
  stemcell: trusty
  persistent_disk_type: 100GB
  networks:
  - name: default
  azs:
  - z1
  - z2

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false
